EXTERN dynMemNameLength
EXTERN dynMemNameOP1
EXTERN dynMemName
EXTERN dynMemOffset

EXTERN zVARs
EXTERN zVARcount

EXTERN stackNameLength
EXTERN stackNameOP1
EXTERN stackName

EXTERN headerBegin
EXTERN headerEnd
EXTERN headerForwardBegin
EXTERN headerForwardEnd
EXTERN headerVersion
EXTERN headerStaticStart
EXTERN headerPCStart
EXTERN headerGlobalStart
EXTERN headerObjectStart
EXTERN headerAbbrevStart

DEFC sliceSize = 0x1f00
