EXTERN opcodeNumber
EXTERN instructionBuffer

EXTERN opcode
EXTERN operandTypes
EXTERN instructionRest
EXTERN twoOPResult
EXTERN oneOPResult

EXTERN zOPcount

EXTERN zOPs
EXTERN zOP1
EXTERN zOP2
EXTERN zOP3
EXTERN zOP4
EXTERN zOP5
EXTERN zOP6
EXTERN zOP7
EXTERN zOP8

EXTERN zVARs
EXTERN zVARcount

EXTERN storyPC

EXTERN writeVariable
EXTERN readVariable
EXTERN doBranch
EXTERN parseBranchBytes
EXTERN objectSeek
